create table suivi_materiel
(
    ID int NOT NULL AUTO_INCREMENT,
    MATERIEL VARCHAR(100) NOT NULL,
    NOM VARCHAR(50) NOT NULL,
    TEL int,
    EMAIL VARCHAR(50),
    DATE_EMPRUNT DATETIME DEFAULT CURRENT_TIMESTAMP, -- a vérifier
    DATE_RETOUR DATE
)


create table texte_factures
(
    ID int NOT NULL AUTO_INCREMENT,
    CATEGORIE VARCHAR(50) NOT NULL,
    TEXTE_FR VARCHAR NOT NULL,
    TEXTE_NL VARCHAR NOT NULL
)


create table factures
(
    ID int NOT NULL AUTO_INCREMENT,
    ID_CLIENT int NOT NULL,
    ID_DEVIS int NOT NULL,
    DATE_DEVIS DATETIME DEFAULT CURRENT_TIMESTAMP, -- a vérifier
    DATE_ECHEANCE DATE,
    DATE_FIN_TRAVAUX DATE,
    TAUX_TVA DOUBLE(3,2),	 -- 0.21 ou autre
    COMMENTAIRE CHAR,
    MONTANT,
    ID_TEXTE_TVA,
    ID_TEXTE_TRAVAUX,
    TEXTE_TRAVAUX
)
