create table suivi_materiel
(
    ID_SUIVI_MATERIEL INT NOT NULL AUTO_INCREMENT,
    MATERIEL VARCHAR(100) NOT NULL,
    NOM VARCHAR(50) NOT NULL,
    TEL INT,
    EMAIL VARCHAR(50),
    DATE_EMPRUNT DATETIME DEFAULT CURRENT_TIMESTAMP, -- a vérifier
    DATE_RETOUR DATE
)


create table texte_factures
(
    ID_TEXTE_FACTURE INT NOT NULL AUTO_INCREMENT,
    CATEGORIE VARCHAR(50) NOT NULL,
    TEXTE_FR VARCHAR NOT NULL,
    TEXTE_NL VARCHAR NOT NULL,
    CONSTRAINT pk__texte_facture PRIMARY KEY (ID_TEXTE_FACTURE)
)


create table factures
(
    ID_FACTURE INT NOT NULL AUTO_INCREMENT,
    ID_CLIENT INT NOT NULL,
    ID_DEVIS INT NOT NULL,
    DATE_DEVIS DATETIME DEFAULT CURRENT_TIMESTAMP, -- a vérifier
    DATE_ECHEANCE DATE,
    DATE_FIN_TRAVAUX DATE,
    TAUX_TVA DOUBLE(3,2),	 -- 0.21 ou autre
    COMMENTAIRE CHAR,
    MONTANT INT,
    ID_TEXTE_TVA INT,
    ID_TEXTE_TRAVAUX INT,
    TEXTE_TRAVAUX CHAR,
    ID_TEXTE_FACTURE INT NOT NULL AUTO_INCREMENT,
    CONSTRAINT pk__factures PRIMARY KEY (ID_FACTURE),
    CONSTRAINT fk__factures__texte_factures FOREIGN KEY (ID_TEXTE_FACTURE) REFERENCES texte_factures (ID_TEXTE_FACTURE)
)
